# Generated by Django 6.0.3 on 2026-03-06 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='resource_file',
            field=models.FileField(blank=True, null=True, upload_to='module_resources/'),
        ),
        migrations.AddField(
            model_name='module',
            name='resource_links',
            field=models.TextField(blank=True),
        ),
    ]
